config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  root "pages#home"
  get "pages/home", to: "pages#home"

  # resources :recipes
  ## this line provides the following routes
#       recipes GET    /recipes(.:format)          recipes#index
#             POST   /recipes(.:format)          recipes#create
#  new_recipe GET    /recipes/new(.:format)      recipes#new
# edit_recipe GET    /recipes/:id/edit(.:format) recipes#edit
#      recipe GET    /recipes/:id(.:format)      recipes#show
#             PATCH  /recipes/:id(.:format)      recipes#update
#             PUT    /recipes/:id(.:format)      recipes#update
#             DELETE /recipes/:id(.:format)      recipes#destroy

	get "/recipes", to: "recipes#index"
	## as: "recipe" will add recipe path to the prefix
	get "/recipes/:id", to: "recipes#show", as: "recipe"

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/chef.rb
class Chef < ApplicationRecord
	# before saving a chef object takes the email of that object
	# references it by using self and turn it to downcase then save it
	before_save {self.email = email.downcase}
	## Add validation to chefs
	validates :chefname, presence: true, length: {maximum: 30}
	VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
	validates :email, presence: true, length: {maximum: 255},
				format: {with: VALID_EMAIL_REGEX},
				uniqueness: { case_sensitive: false }

	has_many :recipes #note recipes is plural
end

app/models/recipe.rb
class Recipe < ApplicationRecord
	validates :name, presence: true
	validates :description, presence: true, length: {minimum: 5, maximum: 500}
	belongs_to :chef #chef is singular
	## This says that chef id needs to be present at all times regardless
	## of when this is run
	validates :chef_id, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController

	def home
	end
end

app/controllers/recipes_controller.rb
class RecipesController < ApplicationController

	def index
		@recipes = Recipe.all
	end

	def show
		## need to grab the id from the params hash that's getting submitted
		## in the get request
		## We'll find a recipe from the database by the id
		## since it's a hash we can grab it 
		@recipe = Recipe.find(params[:id])
	end

end

app/helpers/application_helper.rb
module ApplicationHelper

	## place where we put in all of our methods that we'll be using in our 
	## views
	## methods we write and define here are available for our views to use

	## define a gravatar method that'll go to the web and grab an image
	## that's associated with the gravatar
	## pass in the option to change the size with a default size defined
	## if we don't send in size then we use default of 80
	def gravatar_for(user, options = {size:80})
		## we need to pass in the user object
		## when we pass in user object to this method it'll grab the email
		## address for this user then it'll store the hex digest of that
		## as the gravatar id
		gravatar_id = Digest::MD5::hexdigest(user.email.downcase)
		## the below line is so we can alter the size of the image
		size = options[:size]
		## now we need to form the url
		gravatar_url = "https://secure.gravatar.com/avatar/#{gravatar_id}?s=#{size}"
		## must return the image in an image tag
		image_tag(gravatar_url, alt: user.chefname, class: "img-circle")
	end

end

app/views/layouts/_footer.html.erb
<footer class="footer">
	<small>
		<strong> <a href="#"> Web development app in Rails </a>> </strong>
		by
		<em> <a href="#"> Kenan Abdulkarim </a> </em> 
	</small> 

	<nav>
		<ul>
			<li> <%= link_to "About", "#" %> </li>
		</ul>
	</nav>

</footer>

app/views/layouts/_navigation.html.erb
<!-- When we want to update or add custom CSS go to custom.css.scss -->
<nav class="navbar navbar-default">
  <div class="container-fluid">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <!-- <a class="navbar-brand" href="#">Brand</a> -->
      <%= link_to "MyRecipes", root_path, class: "navbar-brand", id: "logo" %>
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav">
        <li class="active"><a href="#">Link <span class="sr-only">(current)</span></a></li>
        <li><a href="#">Link</a></li>
        <li class="dropdown">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Dropdown <span class="caret"></span></a>
          <ul class="dropdown-menu">
            <li><a href="#">Action</a></li>
            <li><a href="#">Another action</a></li>
            <li><a href="#">Something else here</a></li>
            <li role="separator" class="divider"></li>
            <li><a href="#">Separated link</a></li>
            <li role="separator" class="divider"></li>
            <li><a href="#">One more separated link</a></li>
          </ul>
        </li>
      </ul>
      <form class="navbar-form navbar-left">
        <div class="form-group">
          <input type="text" class="form-control" placeholder="Search">
        </div>
        <button type="submit" class="btn btn-default">Submit</button>
      </form>
      <ul class="nav navbar-nav navbar-right">
        <li><a href="#">Link</a></li>
        <li class="dropdown">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Dropdown <span class="caret"></span></a>
          <ul class="dropdown-menu">
            <li><a href="#">Action</a></li>
            <li><a href="#">Another action</a></li>
            <li><a href="#">Something else here</a></li>
            <li role="separator" class="divider"></li>
            <li><a href="#">Separated link</a></li>
          </ul>
        </li>
      </ul>
    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Chefrecipies</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
  	<%= render 'layouts/navigation' %>
    <div class="container">
    	<%= yield %>
    </div>
    <%= render "layouts/footer" %>

  </body>
</html>

app/views/pages/home.html.erb
<div class="jumbotron center">
	<h1>Welcome to ChefRecipes app!</h1>
	<h2>You can create and share your favourite recipes here!</h2>
	<p> <%= link_to "Sign up or log in", "#", class: "btn btn-danger btn-lg btn-xlarge" %> </p>
</div>

<div class="row">
    <div class="col-lg-4">
      <h2>Heading</h2>
      <p >Donec id elit non mi porta gravida at eget metus. Fusce dapibus, tellus ac cursus commodo, tortor mauris condimentum nibh, ut fermentum massa justo sit amet risus. Etiam porta sem malesuada magna mollis euismod. Donec sed odio dui. </p>
      <p><a class="btn btn-primary btn-xlarge" href="#" role="button">View details &raquo;</a></p>
    </div>
    <div class="col-lg-4">
      <h2>Heading</h2>
      <p>Donec id elit non mi porta gravida at eget metus. Fusce dapibus, tellus ac cursus commodo, tortor mauris condimentum nibh, ut fermentum massa justo sit amet risus. Etiam porta sem malesuada magna mollis euismod. Donec sed odio dui. </p>
      <p><a class="btn btn-primary btn-xlarge" href="#" role="button">View details &raquo;</a></p>
   </div>
    <div class="col-lg-4">
      <h2>Heading</h2>
      <p>Donec sed odio dui. Cras justo odio, dapibus ac facilisis in, egestas eget quam. Vestibulum id ligula porta felis euismod semper. Fusce dapibus, tellus ac cursus commodo, tortor mauris condimentum nibh, ut fermentum massa.</p>
      <p><a class="btn btn-primary btn-xlarge" href="#" role="button">View details &raquo;</a></p>
    </div>
  </div>

app/views/recipes/index.html.erb
<%= render "shared/page_title", title: "showing all recipes" %>

<% @recipes.each do |recipe| %>
	<div class="row"> 
		<div class="col-md-2"> 
			<section class="chef-info center">
				<%= gravatar_for(recipe.chef, size: 120) %>
			</section>
		</div>
		<div class="col-md-8 well">
			<h4> <%= link_to recipe.name, recipe_path(recipe) %> </h4>
			<p> <%= truncate(recipe.description, length: 150)%> </p>
			<p>
				<span class="quiet"> <small> Created <%= time_ago_in_words(recipe.created_at) %> ago </small> </span>
			</p>
		</div>
	</div>

<% end %>

app/views/recipes/show.html.erb
<%= render "shared/page_title", title: @recipe.name %>
<!-- this @recipe name will get passed in to my view as this title object -->
<div class="well col-md-8 col-md-offset-2">
	<h4 class="center description"> <strong>Steps: </strong> </h4>
	<hr />
	<%= simple_format(@recipe.description) %>
	<hr />
	<div class="pull-right">
		<p class="center">
			<em> Created by: </em> 
		</p>
		<p class="center">
			<%= link_to gravatar_for(@recipe.chef), recipe_path %>
		</p>
		<p class="center">
			<small> <%= @recipe.chef.chefname.capitalize %> </small>
			<div class="pull-right"> <%= time_ago_in_words(@recipe.created_at) %> ago </div>
		</p>
	</div> 
</div>

app/views/shared/_page_title.html.erb
<h1 align="center"><%= title.capitalize %> </h1>
<hr/>
<!-- use gravatars -->